services:
  controlplane:
    environment:
      - APP_PORT=3000
      - RUST_LOG=debug
    build:
      context: .
      args:
        BIN_NAME: mtccontrolplane
        APP_PORT: 3000
    ports:
      - "8000:3000"
